In [2]:
import pandas as pd #as pd just changes the access name

In [3]:
property_data = pd.read_csv("data/Property_Assessment_Data_(Current_Calendar_Year)_20251030.csv") # this is a DataFrame

C:\Users\mcimo\AppData\Local\Temp\ipykernel_22820\2313772612.py:1: DtypeWarning: Columns (0: Suite) have mixed types. Specify dtype option on import or set low_memory=False.
  property_data = pd.read_csv("data/Property_Assessment_Data_(Current_Calendar_Year)_20251030.csv") # this is a DataFrame

In [4]:
property_data.head() # pulls the first 5 data rows

,Account Number,Suite,House Number,Street Name,Neighbourhood ID,Neighbourhood,Ward,Assessed Value,Tax Class,Garage,Assessment Class 1,Assessment Class 2,Assessment Class 3,Assessment Class % 1,Assessment Class % 2,Assessment Class % 3,Latitude,Longitude,Point Location
0,4058129,NaN,870.0,ABBOTTSFIELD ROAD NW,2010.0,ABBOTTSFIELD,Métis,150000,Residential,N,RESIDENTIAL,NaN,NaN,100,NaN,NaN,53.576329,-113.392304,POINT (-113.39230350026378 53.57632901357068)
1,4058137,NaN,872.0,ABBOTTSFIELD ROAD NW,2010.0,ABBOTTSFIELD,Métis,149500,Residential,N,RESIDENTIAL,NaN,NaN,100,NaN,NaN,53.576329,-113.392304,POINT (-113.39230350026378 53.57632901357068)
2,4058145,NaN,874.0,ABBOTTSFIELD ROAD NW,2010.0,ABBOTTSFIELD,Métis,151500,Residential,N,RESIDENTIAL,NaN,NaN,100,NaN,NaN,53.576329,-113.392304,POINT (-113.39230350026378 53.57632901357068)
3,4058152,NaN,876.0,ABBOTTSFIELD ROAD NW,2010.0,ABBOTTSFIELD,Métis,147000,Residential,N,RESIDENTIAL,NaN,NaN,100,NaN,NaN,53.576329,-113.392304,POINT (-113.39230350026378 53.57632901357068)
4,4058160,NaN,878.0,ABBOTTSFIELD ROAD NW,2010.0,ABBOTTSFIELD,Métis,153500,Residential,N,RESIDENTIAL,NaN,NaN,100,NaN,NaN,53.576329,-113.392304,POINT (-113.39230350026378 53.57632901357068)

In [5]:
property_data.info() # provides information about the DataFrame

<class 'pandas.DataFrame'>
RangeIndex: 431706 entries, 0 to 431705
Data columns (total 19 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   Account Number        431706 non-null  int64
 1   Suite                 82839 non-null   object
 2   House Number          386360 non-null  float64
 3   Street Name           386360 non-null  str
 4   Neighbourhood ID      423470 non-null  float64
 5   Neighbourhood         431706 non-null  str
 6   Ward                  423470 non-null  str
 7   Assessed Value        431706 non-null  int64
 8   Tax Class             431706 non-null  str
 9   Garage                431706 non-null  str
 10  Assessment Class 1    431706 non-null  str
 11  Assessment Class 2    1096 non-null    str
 12  Assessment Class 3    283 non-null     str
 13  Assessment Class % 1  431706 non-null  int64
 14  Assessment Class % 2  1096 non-null    float64
 15  Assessment Class % 3  283 non-null     float64
 16  Latitude              431706 non-null  float64
 17  Longitude             431706 non-null  float64
 18  Point Location        431706 non-null  str
dtypes: float64(6), int64(3), object(1), str(9)
memory usage: 62.6+ MB

In [6]:
property_data.shape # returns (rows, columns)

(431706, 19)

In [7]:
property_data.describe() # provides basic data statistics

,Account Number,House Number,Neighbourhood ID,Assessed Value,Assessment Class % 1,Assessment Class % 2,Assessment Class % 3,Latitude,Longitude
count,4.317060e+05,386360.000000,423470.000000,4.317060e+05,431706.000000,1096.000000,283.000000,431706.000000,431706.000000
mean,7.932009e+06,7715.353792,4274.007878,5.097698e+05,99.952975,17.537409,3.243816,53.517496,-113.514320
std,3.266791e+06,5494.706696,1756.729000,3.770018e+06,1.214058,15.312706,3.522056,0.068877,0.085176
min,1.001007e+06,1.000000,1010.000000,0.000000e+00,41.000000,1.000000,1.000000,53.338595,-113.713318
25%,4.763971e+06,2513.750000,2660.000000,1.800000e+05,100.000000,3.000000,1.000000,53.457364,-113.573817
50%,9.985830e+06,7916.000000,4487.000000,3.690000e+05,100.000000,13.000000,2.000000,53.519346,-113.510660
75%,1.027426e+07,11431.000000,5579.000000,5.005000e+05,100.000000,32.000000,4.000000,53.572620,-113.448507
max,1.131654e+07,51175.000000,8889.000000,1.289650e+09,100.000000,50.000000,24.000000,53.715150,-113.278411

In [8]:
property_data["Neighbourhood"].unique() # we can use our column names as keys to access data. unique returns the unique entries

<StringArray>
[                   'ABBOTTSFIELD',                          'ALBANY',
                  'ALBERTA AVENUE',         'ALBERTA PARK INDUSTRIAL',
                           'ALCES',                      'ALDERGROVE',
                          'ALLARD',                       'ALLENDALE',
                       'AMBLESIDE',                  'ANTHONY HENDAY',
 ...
                      'WINDERMERE',                 'WINDERMERE AREA',
                    'WINDSOR PARK', 'WINTERBURN INDUSTRIAL AREA EAST',
 'WINTERBURN INDUSTRIAL AREA WEST',                       'WOODCROFT',
        'YELLOWHEAD CORRIDOR EAST',        'YELLOWHEAD CORRIDOR WEST',
                            'YORK',           'YOUNGSTOWN INDUSTRIAL']
Length: 406, dtype: str

In [10]:
downtown_properties = property_data[property_data["Neighbourhood"] == 'DOWNTOWN'] # pulls all data where neighbourgood == downtown
print(f"Number of properties in downtown {downtown_properties.shape[0]}") # lists the # of properties

downtown_properties.head()

Number of properties in downtown 10307

,Account Number,Suite,House Number,Street Name,Neighbourhood ID,Neighbourhood,Ward,Assessed Value,Tax Class,Garage,Assessment Class 1,Assessment Class 2,Assessment Class 3,Assessment Class % 1,Assessment Class % 2,Assessment Class % 3,Latitude,Longitude,Point Location
106995,1018019,NaN,10040.0,103 STREET NW,1090.0,DOWNTOWN,O-day'min,500,Non Residential,N,COMMERCIAL,NaN,NaN,100,NaN,NaN,53.540052,-113.498326,POINT (-113.49832591329127 53.54005220261335)
106996,1018027,NaN,10405.0,JASPER AVENUE NW,1090.0,DOWNTOWN,O-day'min,0,Non Residential,N,COMMERCIAL,NaN,NaN,100,NaN,NaN,53.540587,-113.500165,POINT (-113.50016547038064 53.54058675150321)
106997,1018035,NaN,10808.0,99 AVENUE NW,1090.0,DOWNTOWN,O-day'min,16343500,Non Residential,N,COMMERCIAL,NaN,NaN,100,NaN,NaN,53.537776,-113.507119,POINT (-113.50711890782267 53.537776320029145)
106998,1024140,NaN,9839.0,JASPER AVENUE NW,1090.0,DOWNTOWN,O-day'min,150000,Non Residential,N,COMMERCIAL,NaN,NaN,100,NaN,NaN,53.540915,-113.487252,POINT (-113.48725182521747 53.54091465180801)
106999,1033141,NaN,10820.0,100 AVENUE NW,1090.0,DOWNTOWN,O-day'min,12290500,Non Residential,N,COMMERCIAL,NaN,NaN,100,NaN,NaN,53.539232,-113.507880,POINT (-113.5078803891802 53.539231747129705)

In [12]:
sorted_downtown = downtown_properties.sort_values(by="Assessed Value", ascending=False)
sorted_downtown.head()

,Account Number,Suite,House Number,Street Name,Neighbourhood ID,Neighbourhood,Ward,Assessed Value,Tax Class,Garage,Assessment Class 1,Assessment Class 2,Assessment Class 3,Assessment Class % 1,Assessment Class % 2,Assessment Class % 3,Latitude,Longitude,Point Location
117266,11012019,NaN,10700.0,104 AVENUE NW,1090.0,DOWNTOWN,O-day'min,342370500,Non Residential,N,COMMERCIAL,COMMERCIAL,NaN,99,1.0,NaN,53.547271,-113.507548,POINT (-113.50754750803071 53.54727130295685)
107029,3010113,NaN,10111.0,104 AVENUE NW,1090.0,DOWNTOWN,O-day'min,303790500,Non Residential,N,COMMERCIAL,NaN,NaN,100,NaN,NaN,53.545713,-113.494631,POINT (-113.49463129239268 53.54571273130205)
116496,10854737,NaN,10220.0,103 AVENUE NW,1090.0,DOWNTOWN,O-day'min,284566500,Non Residential,N,COMMERCIAL,NaN,NaN,100,NaN,NaN,53.545391,-113.497000,POINT (-113.49700047375993 53.545390875408884)
116107,10841805,NaN,9804.0,107 STREET NW,1090.0,DOWNTOWN,O-day'min,269688500,Non Residential,N,COMMERCIAL,NaN,NaN,100,NaN,NaN,53.533957,-113.505303,POINT (-113.50530303364825 53.533957217542564)
115226,10507383,NaN,10175.0,101 STREET NW,1090.0,DOWNTOWN,O-day'min,269044500,Non Residential,N,COMMERCIAL,NaN,NaN,100,NaN,NaN,53.542427,-113.493005,POINT (-113.49300518558233 53.54242689204102)

In [13]:
print(sorted_downtown[:10]) # I can still treat this as a list, it's just not as nice to look at.

        Account Number Suite  House Number       Street Name  \
117266        11012019   NaN       10700.0     104 AVENUE NW
107029         3010113   NaN       10111.0     104 AVENUE NW
116496        10854737   NaN       10220.0     103 AVENUE NW
116107        10841805   NaN        9804.0     107 STREET NW
115226        10507383   NaN       10175.0     101 STREET NW
117287        11161319   NaN       10423.0     101 STREET NW
107219         3121522   NaN        9700.0  JASPER AVENUE NW
109930         9981060   NaN       10155.0     102 STREET NW
107004         1066331   NaN       10180.0     101 STREET NW
115231        10713425   NaN       10215.0     108 STREET NW

        Neighbourhood ID Neighbourhood       Ward  Assessed Value  \
117266            1090.0      DOWNTOWN  O-day'min       342370500
107029            1090.0      DOWNTOWN  O-day'min       303790500
116496            1090.0      DOWNTOWN  O-day'min       284566500
116107            1090.0      DOWNTOWN  O-day'min       269688500
115226            1090.0      DOWNTOWN  O-day'min       269044500
117287            1090.0      DOWNTOWN  O-day'min       255188500
107219            1090.0      DOWNTOWN  O-day'min       146280500
109930            1090.0      DOWNTOWN  O-day'min       138813500
107004            1090.0      DOWNTOWN  O-day'min       134928000
115231            1090.0      DOWNTOWN  O-day'min       110509500

              Tax Class Garage Assessment Class 1 Assessment Class 2  \
117266  Non Residential      N         COMMERCIAL         COMMERCIAL
107029  Non Residential      N         COMMERCIAL                NaN
116496  Non Residential      N         COMMERCIAL                NaN
116107  Non Residential      N         COMMERCIAL                NaN
115226  Non Residential      N         COMMERCIAL                NaN
117287  Non Residential      N         COMMERCIAL                NaN
107219  Non Residential      N         COMMERCIAL                NaN
109930  Non Residential      N         COMMERCIAL                NaN
107004  Non Residential      N         COMMERCIAL                NaN
115231  Non Residential      N         COMMERCIAL                NaN

       Assessment Class 3  Assessment Class % 1  Assessment Class % 2  \
117266                NaN                    99                   1.0
107029                NaN                   100                   NaN
116496                NaN                   100                   NaN
116107                NaN                   100                   NaN
115226                NaN                   100                   NaN
117287                NaN                   100                   NaN
107219                NaN                   100                   NaN
109930                NaN                   100                   NaN
107004                NaN                   100                   NaN
115231                NaN                   100                   NaN

        Assessment Class % 3   Latitude   Longitude  \
117266                   NaN  53.547271 -113.507548
107029                   NaN  53.545713 -113.494631
116496                   NaN  53.545391 -113.497000
116107                   NaN  53.533957 -113.505303
115226                   NaN  53.542427 -113.493005
117287                   NaN  53.547688 -113.492095
107219                   NaN  53.542819 -113.486685
109930                   NaN  53.541705 -113.494644
107004                   NaN  53.542610 -113.494642
115231                   NaN  53.543810 -113.505666

                                        Point Location
117266   POINT (-113.50754750803071 53.54727130295685)
107029   POINT (-113.49463129239268 53.54571273130205)
116496  POINT (-113.49700047375993 53.545390875408884)
116107  POINT (-113.50530303364825 53.533957217542564)
115226   POINT (-113.49300518558233 53.54242689204102)
117287    POINT (-113.4920945712609 53.54768788752229)
107219   POINT (-113.48668479938223 53.54281857874582)
109930   POINT (-113.49464390513306 53.54170537801964)
107004   POINT (-113.49464155973786 53.54261029845581)
115231  POINT (-113.50566646028214 53.543810376967556)

In [17]:
print(sorted_downtown[["House Number", "Street Name", "Assessed Value"]][:10]) # acts like an SQL Select

        House Number       Street Name  Assessed Value
117266       10700.0     104 AVENUE NW       342370500
107029       10111.0     104 AVENUE NW       303790500
116496       10220.0     103 AVENUE NW       284566500
116107        9804.0     107 STREET NW       269688500
115226       10175.0     101 STREET NW       269044500
117287       10423.0     101 STREET NW       255188500
107219        9700.0  JASPER AVENUE NW       146280500
109930       10155.0     102 STREET NW       138813500
107004       10180.0     101 STREET NW       134928000
115231       10215.0     108 STREET NW       110509500

In [19]:
sorted_properties = property_data.sort_values(by="Assessed Value", ascending = False)
sorted_properties.head()

,Account Number,Suite,House Number,Street Name,Neighbourhood ID,Neighbourhood,Ward,Assessed Value,Tax Class,Garage,Assessment Class 1,Assessment Class 2,Assessment Class 3,Assessment Class % 1,Assessment Class % 2,Assessment Class % 3,Latitude,Longitude,Point Location
357664,3054384,NaN,8882.0,170 STREET NW,4520.0,SUMMERLEA,sipiwiyiniwak,1289649500,Non Residential,N,COMMERCIAL,COMMERCIAL,NaN,97,3.0,NaN,53.522326,-113.622965,POINT (-113.6229648999618 53.52232562629508)
388670,7012578,NaN,11404.0,89 AVENUE NW,5520.0,UNIVERSITY OF ALBERTA,papastew,1145546000,Non Residential,N,COMMERCIAL,NaN,NaN,100,NaN,NaN,53.526846,-113.525760,POINT (-113.52575973116004 53.52684618498003)
388682,9992482,NaN,11305.0,83 AVENUE NW,5520.0,UNIVERSITY OF ALBERTA,papastew,602640500,Non Residential,N,COMMERCIAL,NaN,NaN,100,NaN,NaN,53.520439,-113.523155,POINT (-113.52315486414373 53.52043938871529)
388683,9996778,NaN,11203.0,87 AVENUE NW,5520.0,UNIVERSITY OF ALBERTA,papastew,423062000,Non Residential,N,COMMERCIAL,NaN,NaN,100,NaN,NaN,53.522158,-113.523168,POINT (-113.5231682055771 53.52215844236709)
388661,4025383,NaN,11404.0,UNIVERSITY AVENUE NW,5520.0,UNIVERSITY OF ALBERTA,papastew,410740000,Non Residential,N,COMMERCIAL,NaN,NaN,100,NaN,NaN,53.518002,-113.527585,POINT (-113.52758487679392 53.51800224375652)

In [25]:
residential_properties = sorted_properties[sorted_properties["Tax Class"] == 'Residential']
residential_properties = residential_properties[residential_properties["Assessment Class 2"] != "COMMERCIAL"]
residential_properties.head()

,Account Number,Suite,House Number,Street Name,Neighbourhood ID,Neighbourhood,Ward,Assessed Value,Tax Class,Garage,Assessment Class 1,Assessment Class 2,Assessment Class 3,Assessment Class % 1,Assessment Class % 2,Assessment Class % 3,Latitude,Longitude,Point Location
178415,3020765,NaN,1230.0,127 STREET SW,5456.0,HERITAGE VALLEY AREA,Ipiihkoohkanipiaohtsi,16507000,Residential,N,RESIDENTIAL,NaN,NaN,100,NaN,NaN,53.421090,-113.547141,POINT (-113.54714144221592 53.421089540804516)
301927,1108380,NaN,15623.0,CAMPBELL ROAD NW,3360.0,RAMPART INDUSTRIAL,Anirniq,14555000,Residential,N,RESIDENTIAL,NaN,NaN,100,NaN,NaN,53.617930,-113.584253,POINT (-113.5842528096102 53.617929972664726)
163838,10003476,NaN,18350.0,127 STREET NW,3490.0,GOODRIDGE CORNERS,Anirniq,14330000,Residential,N,RESIDENTIAL,NaN,NaN,100,NaN,NaN,53.645379,-113.552919,POINT (-113.55291904581743 53.645378724811366)
48426,10884511,NaN,9323.0,101A AVENUE NW,1020.0,BOYLE STREET,O-day'min,13797500,Residential,N,RESIDENTIAL,RESIDENTIAL,NaN,81,19.0,NaN,53.544464,-113.476520,POINT (-113.47651960567521 53.54446435818227)
219550,1868496,NaN,9703.0,185 STREET NW,4240.0,LA PERLE,Nakota Isga,13794500,Residential,Y,RESIDENTIAL,NaN,NaN,100,NaN,NaN,53.533026,-113.640228,POINT (-113.64022755265364 53.53302641085053)